# SPDX-FileCopyrightText: 2024 Alexandru Fikl <alexfikl@gmail.com>
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "papis_uefiscdi"
SPDX-PackageSupplier = "Alexandru Fikl <alexfikl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/alexfikl/papis-uefiscdi"

[[annotations]]
path = ["docs/*.rst", "docs/justfile", "docs/requirements.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "justfile",
    "README.rst",
    "pyproject.toml",
    "requirements*.in",
    "requirements*.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".gitignore", ".github/**.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Alexandru Fikl <alexfikl@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
